[build]
  publish = "public"            # The directory where Netlify will look for static files
  functions = "netlify/functions"  # The directory where your serverless functions are

[dev]
  functions = "netlify/functions"
  publish = "public"
